### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '.editorconfig'

### ISSUE THREAD

**Issue by MeetMatthewBennett** [1000ch/atom-cssfmt#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [cssfmt](https://github.com/1000ch/atom-cssfmt) package, v1.0.9
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '.editorconfig'

```
At fs.js:519

Error: ENOENT: no such file or directory, open '.editorconfig'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:396:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at Object.<anonymous> (/Users/Matt/.atom/packages/cssfmt/node_modules/cssfmt/node_modules/editorconfig-indent/index.js:2:23)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/Matt/.atom/packages/cssfmt/node_modules/cssfmt/lib/config.js:3:26)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/Matt/.atom/packages/cssfmt/node_modules/cssfmt/lib/getIndent.js:4:14)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/Matt/.atom/packages/cssfmt/node_modules/cssfmt/lib/formatDecls.js:1:79)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/Matt/.atom/packages/cssfmt/node_modules/cssfmt/lib/formatAtRules.js:2:19)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/Matt/.atom/packages/cssfmt/node_modules/cssfmt/index.js:4:21)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/Matt/.atom/packages/cssfmt/index.js:7:15)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:759:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:261:14)
  at PackageDetailView.module.exports.PackageDetailView.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:212:26)
  at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:156:12)
  at PackageDetailView.module.exports.PackageDetailView.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:168:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:298:17
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:588:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:379:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
  2x -1:22.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:12.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:55.5.0 settings-view:install-packages-and-themes (atom-text-editor.editor.is-focused)
     -0:49 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:33.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:33 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.0 core:select-all (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-jsfmt, v0.8.3

# Dev
No dev packages
```

**Comment by msaktype** [comment]
@mattdavben Hi, I'm author of CSSfmt. This is a bug in CSSfmt itself, not atom-cssfmt, and now, I fixed it :) https://github.com/morishitter/cssfmt/issues/32

Please re-install (or update) atom-cssfmt. Thanks.

**Comment by MeetMatthewBennett** [comment]
Thank you!
